"""Reusable alert rule definitions."""

HIGH_ENGINE_TEMP_THRESHOLD = 105.0
LOW_FUEL_THRESHOLD = 15.0
LOW_BATTERY_THRESHOLD = 12.1
LOW_OIL_LIFE_THRESHOLD = 20.0
LOW_COOLANT_THRESHOLD = 30.0
HIGH_BRAKE_WEAR_THRESHOLD = 85.0
LOW_TIRE_PRESSURE_THRESHOLD = 30.0
ENGINE_OVERLOAD_THRESHOLD = 95.0
CRITICAL_HEALTH_SCORE_THRESHOLD = 40
